import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";

const open_SansSans = Open_Sans({
   weight: ["400", "500"],
   subsets: ["latin"],
});

export const metadata = {
   title: "Charivest",
   description: "Generated by charivest",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" suppressHydrationWarning>
         <head>
            <ThemeModeScript />
         </head>
         <body className={`${open_SansSans.className} antialiased`}>
            <Flowbite>{children}</Flowbite>
         </body>
      </html>
   );
}
