import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";

const robotoSans = Roboto({
   weight: ["100", "400", "500", "900"],
   variable: "--font-roboto-sans",
   subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
   weight: ["400", "700"],
   variable: "--font-roboto-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "Charivest",
   description: "Generated by charivest",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" suppressHydrationWarning>
         <head>
            <ThemeModeScript />
         </head>
         <body className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}>
            <Flowbite>{children}</Flowbite>
         </body>
      </html>
   );
}
